#!/bin/bash
# Made by Roy Takanen - March 2023
PASTEBIN_METRICS=$(curl -s https://api.pastebin.fi/metrics)
TOTAL=$(echo $PASTEBIN_METRICS | jq '.pasteCount.total')
PUBLIC=$(echo $PASTEBIN_METRICS | jq '.pasteCount.public')
PRIVATE=$(echo $PASTEBIN_METRICS | jq '.pasteCount.private')

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

echo
printf "Pastebin pastes: $Green$TOTAL$Color_Off ($Purple$PUBLIC$Color_Off public & $Yellow$PRIVATE$Color_Off private)\n"
