#!/bin/bash
# Written by Roy (March 2023)

red="\e[1;31m"
undim="\e[0m"

services=$(curl -s https://status.protokolla.fi/api/v1/endpoints/statuses|jq '.[].results|last|select(.success == false) | "  - " + .hostname')
if [[ ! -z "$services" ]]; then
   echo
   printf "There are services$red DOWN!!!!$undim\n\n"
   echo "$services"
fi
